# Unlearning test run, all eval datasets are commented out, and the downstream evaluations are commented out as well.

run_name: OLMo2-7B-unlearn_books_subset
seed: 42069
dry_run: false

save_folder: ./logs/Olmo2-7B-unlearn_books_subset

model:
  d_model: 4096
  n_heads: 32
  n_layers: 32
  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  rope_theta: 500000
  flash_attention: true
  attention_dropout: 0.0
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm: true
  attention_layer_norm_with_affine: true
  norm_after: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 100278
  embedding_size: 100352
  eos_token_id: 100257
  pad_token_id: 100277
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

softmax_auxiliary_loss: true
auxiliary_loss_multiplier: 1e-5
fused_loss: true

compile: null

optimizer:
  name: adamw
  learning_rate: 0.000061499
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 1

scheduler:
  name: linear_with_warmup
  t_warmup: 0
  alpha_f: 0

tokenizer:
  identifier: tokenizers/allenai_dolma2.json
  truncate_direction: right

save_overwrite: false

save_interval: 1000
save_interval_ephemeral: 250
save_num_checkpoints_to_keep: -1
sharded_checkpointer: olmo_core

save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: https://olmo-checkpoints.org/ai2-llm/peteish7/step928000-unsharded/

restore_dataloader: false
no_pre_train_checkpoint: true

max_duration: 50e9T
stop_at: 11931                  # round(50e9 / (1024 * 4096)) + 10
global_train_batch_size: 1024
device_train_microbatch_size: 2

precision: amp_bf16

fsdp:
  wrapping_strategy: by_block_and_size
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

gen1_gc_interval: 1

eval_interval: 1000
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
# evaluators:
  # - label: all-small-ppl-validation
  #   data:
  #     num_workers: 0
  #     drop_last: true
  #     # generate_doc_lengths: true
  #     memmap_dtype: uint32
  #     datasets:
  #       c4_en-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/c4_en/val/part-0-00000.npy
  #       dolma_books-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_books/val/part-0-00000.npy
  #       dolma_common-crawl-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_common-crawl/val/part-0-00000.npy
  #       dolma_pes2o-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_pes2o/val/part-0-00000.npy
  #       dolma_reddit-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_reddit/val/part-0-00000.npy
  #       dolma_stack-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_stack/val/part-0-00000.npy
  #       dolma_wiki-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/dolma_wiki/val/part-0-00000.npy
  #       ice-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/ice/val/part-0-00000.npy
  #       m2d2_s2orc-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/m2d2_s2orc/val/part-0-00000.npy
  #       pile-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/pile/val/part-0-00000.npy
  #       wikitext_103-validation:
  #         - http://olmo-data.org/eval-data/perplexity/v3_small_dolma2-tokenizer/wikitext_103/val/part-0-00000.npy

  ##########################
  # Downstream evaluations #
  ##########################
  # - label: piqa
  #   type: downstream

  # - label: hellaswag
  #   type: downstream

  # - label: winogrande
  #   type: downstream

  # - label: openbook_qa
  #   type: downstream

  # - label: boolq
  #   type: downstream

  # - label: sciq
  #   type: downstream

  # - label: arc_easy
  #   type: downstream

  # - label: arc_challenge
  #   type: downstream

  # - label: copa
  #   type: downstream

  # - label: commonsense_qa
  #   type: downstream

  # - label: social_iqa
  #   type: downstream

  # - label: mmlu_stem_var
  #   type: downstream

  # - label: mmlu_humanities_var
  #   type: downstream

  # - label: mmlu_social_sciences_var
  #   type: downstream

  # - label: mmlu_other_var
  #   type: downstream

  # - label: mmlu_stem_mc_5shot
  #   type: downstream

  # - label: mmlu_humanities_mc_5shot
  #   type: downstream

  # - label: mmlu_social_sciences_mc_5shot
  #   type: downstream

  # - label: mmlu_other_mc_5shot
  #   type: downstream

  # - label: mmlu_stem_mc_5shot_test
  #   type: downstream

  # - label: mmlu_humanities_mc_5shot_test
  #   type: downstream

  # - label: mmlu_social_sciences_mc_5shot_test
  #   type: downstream

  # - label: mmlu_other_mc_5shot_test
  #   type: downstream

  # - label: basic_arithmetic
  #   type: downstream

  # - label: trivia_qa_wiki_ppl
  #   type: downstream

  # - label: natural_qs_open_ppl
  #   type: downstream

  # - label: arc_easy_ppl
  #   type: downstream

data:
  pad_direction: right
  # generate_doc_lengths: true
  num_workers: 12
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  memmap_dtype: uint32
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    # Local paths here
    - dolma/part-00-00000.npy
    # And so on...