run_name: unlearn-OLMo-7B
seed: 6198
dry_run: false

# Comment out the wandb section if you don't wish to use wandb for logging
# Otherwise update it according to your account info and it's setup on the cluster
wandb:
  name: {run_name}
  project: OLMo-Unlearn
  entity: roloza7-georgia-institute-of-technology
  # group: OLMo-7B

# Matched to OLMo2-7B-stage2-seed42069
model:
  d_model: 4096
  n_heads: 32
  n_layers: 32
  mlp_hidden_size: 22016
  weight_tying: false
  alibi: false
  rope: true
  rope_theta: 500000
  flash_attention: true
  attention_dropout: 0.0
  include_bias: false
  block_type: sequential
  layer_norm_type: rms
  layer_norm_with_affine: true
  layer_norm_eps: 1e-6
  bias_for_layer_norm: false
  attention_layer_norm: true
  attention_layer_norm_with_affine: true
  norm_after: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  vocab_size: 100278
  embedding_size: 100352
  eos_token_id: 100257
  pad_token_id: 100277
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3

softmax_auxiliary_loss: true
auxiliary_loss_multiplier: 1e-5
fused_loss: false # Sad

compile: # causes instability on AMD GPUs
  fullgraph: false

activation_checkpointing: whole_layer

optimizer:
  name: adamw
  learning_rate: 5e-6
  weight_decay: 0.1
  eps: 1e-8
  decay_norm_and_bias: true
  decay_embeddings: false
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 1

# We don't want adam to maintain the OLMo-Phase2 momentum statistics because we flip the sign of the gradients
# So we reset the optimizer state AND warmup the learning rate again
# - Rodrigo
reset_optimizer_state: true

# This might not be necessary
# - Rodrigo
reset_trainer_state: true

scheduler:
  name: cosine_with_warmup
  t_warmup: 1000
  alpha_f: 0.1
  grad_clip_warmup_steps: 1000
  grad_clip_warmup_factor: 10.0

tokenizer:
  identifier: tokenizers/allenai_dolma2.json
  truncate_direction: right

save_folder:  /storage/scratch1/3/rloza3/checkpoints/OLMo-7B/excl-math
# save_folder: 
remote_save_folder: null
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: -1
# Unsharded checkpoints (for final storage)
save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: https://olmo-checkpoints.org/ai2-llm/peteish7/step928000-unsharded/

# Train for 3B tokens
max_duration: 3e8T
global_train_batch_size: 256 # 8 gpus * 4 sequences per microbatch * 8 microbatches per batch
device_train_microbatch_size: 4
time_limit: null

precision: amp_bf16

ddp:
  grad_sync_mode: batch

distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block_and_size
  precision: mixed
  sharding_strategy: SHARD_GRAD_OP

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: 5 # limit how many batches to evaluate on (set to -1 for all batches)
device_eval_batch_size: ${device_train_microbatch_size}

evaluators:

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  - label: copa
    type: downstream

  - label: rte
    type: downstream

  - label: commitment_bank
    type: downstream

  - label: mrpc
    type: downstream

  - label: sst2
    type: downstream

data:
  pad_direction: right
  # generate_doc_lengths: true
  num_workers: 8
  drop_last: true
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  memmap_dtype: uint16
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-00-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-00-00001.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-01-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-02-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-03-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-03-00001.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-04-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-04-00001.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-05-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-06-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-07-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-08-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-09-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-10-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-11-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-12-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-13-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-13-00001.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-14-00000.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-14-00001.npy
    - /storage/scratch1/3/rloza3/math_dolma/tok/part-15-00000.npy
